### PR TITLE
Update to angular 7, rxjs 6

### PR DESCRIPTION
**Pull request by gc23**
*Description of changes:*
Updated to angular 7 and rxjs 6

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awsed** [comment]
I'm getting this error: 

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-11-02T01:03:14.306Z
Hash: cc9ea6a4185f212d9a70
Time: 3679ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 42 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in ../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,55): error TS1005: '>' expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,62): error TS1003: Identifier expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,86): error TS1144: '{' or ';' expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,105): error TS1005: ',' expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,112): error TS1005: '>' expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,118): error TS1109: Expression expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(26,141): error TS1109: Expression expected.
../node_modules/aws-appsync/lib/link/auth-link.d.ts(27,1): error TS1128: Declaration or statement expected.


webpack: Failed to compile.
```

Take a look at the branch I'm testing the Angular 7 upgrade on https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular/tree/angular7 . I'm down to 1 error:

```
Date: 2018-11-02T01:05:38.436Z
Hash: 2244eca91199d9db1272
Time: 8046ms
chunk {main} main.js, main.js.map (main) 1.99 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 94.7 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in src/app/chat-app/chat/chat.component.ts(27,11): error TS2314: Generic type 'AWSAppSyncClient<TCacheShape>'requires 1 type argument(s).
src/app/chat-app/infscroll.directive.ts(37,33): error TS2339: Property 'pairwise' does not exist on type 'Observable<any>'.

ℹ ｢wdm｣: Failed to compile.
```

**Comment by gc23** [comment]
Hi,

Could you try deleting the node_modules folder?
I've tried several builds and all came through, including --aot

**Comment by awsed** [comment]
I got it to build without errors! This is awesome, thank you!

However I am now getting an error after creating a user:

```ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at ChatComponent.push../src/app/chat-app/chat/chat.component.ts.ChatComponent.register (chat.component.ts:92)```

We suspect there might be an issue with the appsync.service.ts service. We'll take a closer look at it.

**Comment by marcoturi** [comment]
@awsed 
To fix, use this code:

```
export function initialize(appSyncService: AppSyncService) {
    return () => appSyncService.init();
}

@NgModule({
    imports: [
        ApolloModule,
    ],
    providers: [
        AppSyncService,
        AuthService,
    ],
})
export class CoreModule {

    public static forRoot(): ModuleWithProviders {
        return {
            ngModule: CoreModule,
            providers: [
                { provide: APP_INITIALIZER, useFactory: initialize, deps: [AppSyncService], multi: true },
                AuthGuard,
                AppSyncService,
            ],
        };
    }

    constructor(@Optional() @SkipSelf() parentModule: CoreModule) {
        throwIfAlreadyLoaded(parentModule, 'CoreModule');
    }
}
```

```
@Injectable()
export class AppSyncService {

    public client;
    // private _client: AWSAppSyncClient<any>;

    constructor() { //
    }

    public async init() {
        const client = new AWSAppSyncClient({
            url: appSyncConfig.graphqlEndpoint,
            region: appSyncConfig.region,
            auth: {
                type: appSyncConfig.authenticationType,
                // jwtToken: session.idToken.jwtToken,
                jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken(),
            },
        });
        this.client = await client.hydrated();
    }
}

```

**Comment by HuguesRousseau** [comment]
@awsed An alternative solution for me was to assign client instead of hydrated and return hydrated() in appsync.service.ts:
`export class AppsyncService {

  // hc;
  _hc;

  constructor() {
    const client = new AWSAppSyncClient({
      url: aws_exports.aws_appsync_graphqlEndpoint,
      region: aws_exports.aws_project_region,
      auth: {
        type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
        jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
      }
    });
    // this.hc = client.hydrated;
    this._hc = client;
  }

  hc() {
    return this._hc.hydrated();
  }
}
`

**Comment by awsed** [comment]
Thank you a lot @HuguesRousseau and @gc23, tested with your code and it's now merged.

**Pull request merged**
